This notebook merges some additional features of the IPEDS data set with the Pell Partnership data set.

In [1]:
import pandas as pd

In [2]:
IPEDS = pd.read_csv('UTF8_delta_public_00_12.csv', header=0)
IPEDS.head()

/var/folders/24/536gs7r91qzd964t2ppqhs6m0000gn/T/ipykernel_1582/1434376919.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  IPEDS = pd.read_csv('UTF8_delta_public_00_12.csv', header=0)

,groupid,academicyear,unitid_linchpin,unitid,isgrouped,instname,TCSName,city,state,zip,...,Iptall1,Iptall2,Iptall3,Iptall4,Iptall5,Iptall6,Iptall7,Iptall8,Ifaculty_instr_headcount,Isalarytotal
0,-475291,2012,475291,475291,0,Brown College-Brooklyn Center,NaN,Brooklyn Center,MN,55430,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
1,-475282,2012,475282,475282,0,Marian Health Careers Center-Van Nuys Campus,NaN,Van Nuys,CA,91411,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
2,-475273,2012,475273,475273,0,Springfield College-School of Human Services,NaN,Springfield,MA,1109,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
3,-475255,2012,475255,475255,0,American Broadcasting School-Online Program,NaN,Oklahoma City,OK,73115,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2
4,-475246,2012,475246,475246,0,Kaplan College-Chesapeake,NaN,Chesapeake,VA,23320,...,-2,-2,-2,-2,-2,-2,-2,-2,-2,-2

Select the features from the IPEDS data set that we what to merge.

In [3]:
IPEDS_sel = IPEDS[['unitid', 'academicyear','admssn', 'applcn']]
IPEDS_sel

       unitid  academicyear  admssn  applcn
0      475291          2012     NaN     NaN
1      475282          2012     NaN     NaN
2      475273          2012     NaN     NaN
3      475255          2012     NaN     NaN
4      475246          2012     NaN     NaN
...       ...           ...     ...     ...
87555  450517          2011    20.0    27.0
87556  450517          2012    76.0    91.0
87557  454209          2010    12.0    14.0
87558  454209          2011    20.0    25.0
87559  454209          2012    33.0    39.0

[87560 rows x 4 columns]

In [4]:
ThePellPartnership = pd.read_csv('ThePellPartnership_EdTrust.csv', header=0)
ThePellPartnership.head()

,IPEDS Unit ID,Institution,State,Sector,Minority-Serving Institution,Number of Undergraduates,Percent Pell Recipients Among Undergraduates,Percent Underrepresented Minorities Among Total Undergraduates,Net Price for Low-Income Students-($0-30K),"Total Pell Dollars Received, 2012-13",2013 6-Year Pell Grant Recipient Graduation Rate,2013 6-Year Non-Pell Grant Recipient Graduation Rate,6-Year Graduation Rate Gap Between Pell and Non-Pell Students,Average 6-Year Pell Grant Recipient Graduation Rate among Peers,Median 6-Year Pell Grant Recipient Graduation Rate Among Peers,Number of Peers with Pell Grad Rate Data,Pell Grant Recipient Graduation Rate Peer Group Rank
0,100654,Alabama A & M University,AL,Public,Historically-Black-College-or-University,4093.0,71.2,95.9,12683.0,13738784.0,NaN,NaN,NaN,32.2,31.2,14.0,NaN
1,100663,University of Alabama at Birmingham,AL,Public,No,11291.0,35.1,28.9,12361.0,17022497.0,44.9,56.8,11.9,49.7,48.2,16.0,12.0
2,100706,University of Alabama in Huntsville,AL,Public,No,5882.0,32.8,18.6,14652.0,7776157.0,36.0,52.1,16.1,50.8,51.0,13.0,13.0
3,100724,Alabama State University,AL,Public,Historically-Black-College-or-University,5130.0,82.7,96.0,12342.0,18675520.0,NaN,NaN,NaN,33.1,35.0,13.0,NaN
4,100751,The University of Alabama,AL,Public,No,28026.0,21.1,14.9,17206.0,24560513.0,51.8,68.8,17.0,61.2,59.4,16.0,16.0

Rename the Pell Partnership ID column to match IPEDS ID column name.

In [5]:
ThePellPartnership = ThePellPartnership.rename(columns={"IPEDS Unit ID": "unitid"})

In [6]:
ThePellPartnership.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 17 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   unitid                                                           1484 non-null   int64
 1   Institution                                                      1484 non-null   object
 2   State                                                            1484 non-null   object
 3   Sector                                                           1484 non-null   object
 4   Minority-Serving Institution                                     1484 non-null   object
 5   Number of Undergraduates                                         1481 non-null   float64
 6   Percent Pell Recipients Among Undergraduates                     1481 non-null   float64
 7   Percent Underrepresented Minorities Among Total Undergraduates   1481 non-null   float64
 8   Net Price for Low-Income Students-($0-30K)                       1479 non-null   float64
 9   Total Pell Dollars Received, 2012-13                             1437 non-null   float64
 10  2013 6-Year Pell Grant Recipient Graduation Rate                 1114 non-null   float64
 11  2013 6-Year Non-Pell Grant Recipient Graduation Rate             1122 non-null   float64
 12  6-Year Graduation Rate Gap Between Pell and Non-Pell Students    1126 non-null   float64
 13  Average 6-Year Pell Grant Recipient Graduation Rate among Peers  1112 non-null   float64
 14  Median 6-Year Pell Grant Recipient Graduation Rate Among Peers   1112 non-null   float64
 15  Number of Peers with Pell Grad Rate Data                         1442 non-null   float64
 16  Pell Grant Recipient Graduation Rate Peer Group Rank             944 non-null    float64
dtypes: float64(12), int64(1), object(4)
memory usage: 197.2+ KB

Select academic year 2012 from the IPEDS data set because the Pell Partnership data set only consists of data from the 2012 acedemic school year.

In [7]:
# Select only the rows where 'academicyear' == 2012 in IPEDS_sel dataframe
IPEDS_sel_2012 = IPEDS_sel[IPEDS_sel['academicyear'] == 2012]

# Merge 'admssn' from IPEDS_sel_2012 with ThePellPartnership using 'unitid' as key
merged_df = pd.merge(IPEDS_sel_2012[['unitid','admssn', 'applcn']], ThePellPartnership, on='unitid', how='inner')

# Print the resulting dataframe
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1393 entries, 0 to 1392
Data columns (total 19 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   unitid                                                           1393 non-null   int64
 1   admssn                                                           1272 non-null   float64
 2   applcn                                                           1272 non-null   float64
 3   Institution                                                      1393 non-null   object
 4   State                                                            1393 non-null   object
 5   Sector                                                           1393 non-null   object
 6   Minority-Serving Institution                                     1393 non-null   object
 7   Number of Undergraduates                                         1393 non-null   float64
 8   Percent Pell Recipients Among Undergraduates                     1393 non-null   float64
 9   Percent Underrepresented Minorities Among Total Undergraduates   1393 non-null   float64
 10  Net Price for Low-Income Students-($0-30K)                       1391 non-null   float64
 11  Total Pell Dollars Received, 2012-13                             1389 non-null   float64
 12  2013 6-Year Pell Grant Recipient Graduation Rate                 1052 non-null   float64
 13  2013 6-Year Non-Pell Grant Recipient Graduation Rate             1060 non-null   float64
 14  6-Year Graduation Rate Gap Between Pell and Non-Pell Students    1063 non-null   float64
 15  Average 6-Year Pell Grant Recipient Graduation Rate among Peers  1065 non-null   float64
 16  Median 6-Year Pell Grant Recipient Graduation Rate Among Peers   1065 non-null   float64
 17  Number of Peers with Pell Grad Rate Data                         1362 non-null   float64
 18  Pell Grant Recipient Graduation Rate Peer Group Rank             903 non-null    float64
dtypes: float64(14), int64(1), object(4)
memory usage: 217.7+ KB

Make sure there are no duplicate ID's after the merge.

In [8]:
# Drop duplicates based on 'unitid'
merged_df = merged_df.drop_duplicates(subset='unitid')

# Print the resulting dataframe
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1393 entries, 0 to 1392
Data columns (total 19 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   unitid                                                           1393 non-null   int64
 1   admssn                                                           1272 non-null   float64
 2   applcn                                                           1272 non-null   float64
 3   Institution                                                      1393 non-null   object
 4   State                                                            1393 non-null   object
 5   Sector                                                           1393 non-null   object
 6   Minority-Serving Institution                                     1393 non-null   object
 7   Number of Undergraduates                                         1393 non-null   float64
 8   Percent Pell Recipients Among Undergraduates                     1393 non-null   float64
 9   Percent Underrepresented Minorities Among Total Undergraduates   1393 non-null   float64
 10  Net Price for Low-Income Students-($0-30K)                       1391 non-null   float64
 11  Total Pell Dollars Received, 2012-13                             1389 non-null   float64
 12  2013 6-Year Pell Grant Recipient Graduation Rate                 1052 non-null   float64
 13  2013 6-Year Non-Pell Grant Recipient Graduation Rate             1060 non-null   float64
 14  6-Year Graduation Rate Gap Between Pell and Non-Pell Students    1063 non-null   float64
 15  Average 6-Year Pell Grant Recipient Graduation Rate among Peers  1065 non-null   float64
 16  Median 6-Year Pell Grant Recipient Graduation Rate Among Peers   1065 non-null   float64
 17  Number of Peers with Pell Grad Rate Data                         1362 non-null   float64
 18  Pell Grant Recipient Graduation Rate Peer Group Rank             903 non-null    float64
dtypes: float64(14), int64(1), object(4)
memory usage: 217.7+ KB

In [9]:
merged_df

,unitid,admssn,applcn,Institution,State,Sector,Minority-Serving Institution,Number of Undergraduates,Percent Pell Recipients Among Undergraduates,Percent Underrepresented Minorities Among Total Undergraduates,Net Price for Low-Income Students-($0-30K),"Total Pell Dollars Received, 2012-13",2013 6-Year Pell Grant Recipient Graduation Rate,2013 6-Year Non-Pell Grant Recipient Graduation Rate,6-Year Graduation Rate Gap Between Pell and Non-Pell Students,Average 6-Year Pell Grant Recipient Graduation Rate among Peers,Median 6-Year Pell Grant Recipient Graduation Rate Among Peers,Number of Peers with Pell Grad Rate Data,Pell Grant Recipient Graduation Rate Peer Group Rank
0,449870,NaN,NaN,University of the West,CA,Private Nonprofit,No,128.0,17.2,15.6,5502.0,99468.0,NaN,NaN,NaN,38.2,42.9,11.0,NaN
1,449764,32.0,36.0,Visible School-Music and Worships Arts College,TN,Private Nonprofit,No,122.0,44.4,14.8,27533.0,244589.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,449658,35.0,67.0,Bais Medrash Toras Chesed,NJ,Private Nonprofit,No,126.0,42.9,0.0,5295.0,248498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,449348,NaN,NaN,Huntsville Bible College,AL,Private Nonprofit,No,102.0,30.4,98.0,10708.0,241407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,448309,NaN,NaN,Shorter College-Professional Studies,GA,Private Nonprofit,No,1252.0,64.6,72.5,25185.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1388,126562,3235.0,5413.0,University of Colorado Denver,CO,Public,No,13103.0,27.8,20.4,9870.0,14829461.0,41.2,40.9,0.0,36.3,34.5,15.0,6.0
1389,206084,NaN,NaN,University of Toledo-Main Campus,OH,Public,No,16837.0,37.9,19.6,12687.0,25959787.0,33.4,52.2,18.8,37.2,36.3,14.0,9.0
1390,137351,11107.0,29194.0,University of South Florida,FL,Public,No,31125.0,41.3,30.1,6688.0,65008116.0,61.5,63.8,2.2,50.3,50.6,14.0,2.0
1391,210304,667.0,1090.0,Warner Pacific College,OR,Private Nonprofit,No,551.0,53.4,17.8,18464.0,4140336.0,26.5,34.5,8.0,35.7,33.2,10.0,9.0
1392,212197,2411.0,3665.0,Elizabethtown College,PA,Private Nonprofit,No,1885.0,21.8,5.4,18683.0,2112120.0,66.7,79.3,12.6,62.5,63.7,14.0,5.0

In [10]:
merged_df = merged_df.dropna()
merged_df

,unitid,admssn,applcn,Institution,State,Sector,Minority-Serving Institution,Number of Undergraduates,Percent Pell Recipients Among Undergraduates,Percent Underrepresented Minorities Among Total Undergraduates,Net Price for Low-Income Students-($0-30K),"Total Pell Dollars Received, 2012-13",2013 6-Year Pell Grant Recipient Graduation Rate,2013 6-Year Non-Pell Grant Recipient Graduation Rate,6-Year Graduation Rate Gap Between Pell and Non-Pell Students,Average 6-Year Pell Grant Recipient Graduation Rate among Peers,Median 6-Year Pell Grant Recipient Graduation Rate Among Peers,Number of Peers with Pell Grad Rate Data,Pell Grant Recipient Graduation Rate Peer Group Rank
14,441937,3304.0,5745.0,California State University-Channel Islands,CA,Public,Hispanic-Serving-Institution,4736.0,39.6,38.7,10665.0,8531522.0,47.6,52.8,5.2,37.0,36.5,12.0,3.0
18,433660,6246.0,9199.0,Florida Gulf Coast University,FL,Public,No,12230.0,34.7,24.9,10778.0,17619384.0,45.0,44.0,0.0,46.8,47.9,14.0,9.0
20,409698,5364.0,10263.0,California State University-Monterey Bay,CA,Public,Hispanic-Serving-Institution,5185.0,47.6,44.2,5334.0,11748041.0,41.4,36.9,0.0,37.1,40.0,14.0,6.0
27,366711,4055.0,9937.0,California State University-San Marcos,CA,Public,Hispanic-Serving-Institution,9929.0,43.1,35.7,8427.0,18153065.0,40.7,49.9,9.2,36.8,38.9,15.0,6.0
29,262129,715.0,1272.0,New College of Florida,FL,Public,No,832.0,28.6,15.7,7007.0,1060041.0,65.5,65.9,0.4,76.0,81.3,13.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1386,230959,1375.0,7984.0,Middlebury College,VT,Private Nonprofit,No,2516.0,11.0,9.2,7357.0,1279762.0,88.7,94.1,5.4,90.8,90.3,15.0,12.0
1388,126562,3235.0,5413.0,University of Colorado Denver,CO,Public,No,13103.0,27.8,20.4,9870.0,14829461.0,41.2,40.9,0.0,36.3,34.5,15.0,6.0
1390,137351,11107.0,29194.0,University of South Florida,FL,Public,No,31125.0,41.3,30.1,6688.0,65008116.0,61.5,63.8,2.2,50.3,50.6,14.0,2.0
1391,210304,667.0,1090.0,Warner Pacific College,OR,Private Nonprofit,No,551.0,53.4,17.8,18464.0,4140336.0,26.5,34.5,8.0,35.7,33.2,10.0,9.0
1392,212197,2411.0,3665.0,Elizabethtown College,PA,Private Nonprofit,No,1885.0,21.8,5.4,18683.0,2112120.0,66.7,79.3,12.6,62.5,63.7,14.0,5.0

## Create a new variable 'addmission rate' using existing features

acceptance rate = total number of admitted students / total number of applicants

In [11]:
#merged_df = merged_df.loc[:, ['unitid', 'admssn', 'applcn']]
merged_df['admssn_rate'] = round((merged_df['admssn'] / merged_df['applcn']) * 100, 1)
merged_df['Number of Undergraduates Recieving Pell Grants'] = round(merged_df['Number of Undergraduates'] * (merged_df['Percent Pell Recipients Among Undergraduates'] / 100), 0)
merged_df['avg_pell_grant_per_student'] = round(merged_df['Total Pell Dollars Received, 2012-13'] / merged_df['Number of Undergraduates Recieving Pell Grants'], 2)

#merged_df['admssn_rate'] = (merged_df['admssn'] / merged_df['applcn']) * 100
merged_df

/var/folders/24/536gs7r91qzd964t2ppqhs6m0000gn/T/ipykernel_1582/4069506832.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['admssn_rate'] = round((merged_df['admssn'] / merged_df['applcn']) * 100, 1)
/var/folders/24/536gs7r91qzd964t2ppqhs6m0000gn/T/ipykernel_1582/4069506832.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Number of Undergraduates Recieving Pell Grants'] = round(merged_df['Number of Undergraduates'] * (merged_df['Percent Pell Recipients Among Undergraduates'] / 100), 0)
/var/folders/24/536gs7r91qzd964t2ppqhs6m0000gn/T/ipykernel_1582/4069506832.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['avg_pell_grant_per_student'] = round(merged_df['Total Pell Dollars Received, 2012-13'] / merged_df['Number of Undergraduates Recieving Pell Grants'], 2)

,unitid,admssn,applcn,Institution,State,Sector,Minority-Serving Institution,Number of Undergraduates,Percent Pell Recipients Among Undergraduates,Percent Underrepresented Minorities Among Total Undergraduates,...,2013 6-Year Pell Grant Recipient Graduation Rate,2013 6-Year Non-Pell Grant Recipient Graduation Rate,6-Year Graduation Rate Gap Between Pell and Non-Pell Students,Average 6-Year Pell Grant Recipient Graduation Rate among Peers,Median 6-Year Pell Grant Recipient Graduation Rate Among Peers,Number of Peers with Pell Grad Rate Data,Pell Grant Recipient Graduation Rate Peer Group Rank,admssn_rate,Number of Undergraduates Recieving Pell Grants,avg_pell_grant_per_student
14,441937,3304.0,5745.0,California State University-Channel Islands,CA,Public,Hispanic-Serving-Institution,4736.0,39.6,38.7,...,47.6,52.8,5.2,37.0,36.5,12.0,3.0,57.5,1875.0,4550.15
18,433660,6246.0,9199.0,Florida Gulf Coast University,FL,Public,No,12230.0,34.7,24.9,...,45.0,44.0,0.0,46.8,47.9,14.0,9.0,67.9,4244.0,4151.60
20,409698,5364.0,10263.0,California State University-Monterey Bay,CA,Public,Hispanic-Serving-Institution,5185.0,47.6,44.2,...,41.4,36.9,0.0,37.1,40.0,14.0,6.0,52.3,2468.0,4760.15
27,366711,4055.0,9937.0,California State University-San Marcos,CA,Public,Hispanic-Serving-Institution,9929.0,43.1,35.7,...,40.7,49.9,9.2,36.8,38.9,15.0,6.0,40.8,4279.0,4242.36
29,262129,715.0,1272.0,New College of Florida,FL,Public,No,832.0,28.6,15.7,...,65.5,65.9,0.4,76.0,81.3,13.0,9.0,56.2,238.0,4453.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1386,230959,1375.0,7984.0,Middlebury College,VT,Private Nonprofit,No,2516.0,11.0,9.2,...,88.7,94.1,5.4,90.8,90.3,15.0,12.0,17.2,277.0,4620.08
1388,126562,3235.0,5413.0,University of Colorado Denver,CO,Public,No,13103.0,27.8,20.4,...,41.2,40.9,0.0,36.3,34.5,15.0,6.0,59.8,3643.0,4070.67
1390,137351,11107.0,29194.0,University of South Florida,FL,Public,No,31125.0,41.3,30.1,...,61.5,63.8,2.2,50.3,50.6,14.0,2.0,38.0,12855.0,5057.03
1391,210304,667.0,1090.0,Warner Pacific College,OR,Private Nonprofit,No,551.0,53.4,17.8,...,26.5,34.5,8.0,35.7,33.2,10.0,9.0,61.2,294.0,14082.78
1392,212197,2411.0,3665.0,Elizabethtown College,PA,Private Nonprofit,No,1885.0,21.8,5.4,...,66.7,79.3,12.6,62.5,63.7,14.0,5.0,65.8,411.0,5138.98

In [12]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 877 entries, 14 to 1392
Data columns (total 22 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   unitid                                                           877 non-null    int64
 1   admssn                                                           877 non-null    float64
 2   applcn                                                           877 non-null    float64
 3   Institution                                                      877 non-null    object
 4   State                                                            877 non-null    object
 5   Sector                                                           877 non-null    object
 6   Minority-Serving Institution                                     877 non-null    object
 7   Number of Undergraduates                                         877 non-null    float64
 8   Percent Pell Recipients Among Undergraduates                     877 non-null    float64
 9   Percent Underrepresented Minorities Among Total Undergraduates   877 non-null    float64
 10  Net Price for Low-Income Students-($0-30K)                       877 non-null    float64
 11  Total Pell Dollars Received, 2012-13                             877 non-null    float64
 12  2013 6-Year Pell Grant Recipient Graduation Rate                 877 non-null    float64
 13  2013 6-Year Non-Pell Grant Recipient Graduation Rate             877 non-null    float64
 14  6-Year Graduation Rate Gap Between Pell and Non-Pell Students    877 non-null    float64
 15  Average 6-Year Pell Grant Recipient Graduation Rate among Peers  877 non-null    float64
 16  Median 6-Year Pell Grant Recipient Graduation Rate Among Peers   877 non-null    float64
 17  Number of Peers with Pell Grad Rate Data                         877 non-null    float64
 18  Pell Grant Recipient Graduation Rate Peer Group Rank             877 non-null    float64
 19  admssn_rate                                                      877 non-null    float64
 20  Number of Undergraduates Recieving Pell Grants                   877 non-null    float64
 21  avg_pell_grant_per_student                                       877 non-null    float64
dtypes: float64(17), int64(1), object(4)
memory usage: 157.6+ KB

# Export the new data set as a CSV

In [13]:
# save the dataframe as a CSV file
merged_df.to_csv('ThePellPartnership_EdTrust_NEW.csv', index=False)